/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'pricePaise' : IDL.Nat,
  'image' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [Product],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'pricePaise' : IDL.Nat,
    'image' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [Product],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };